spring:
  cloud:
    aws:
      ses:
        enabled: false
      credentials:
        secret-key: ${AWS_SECRET_KEY}
        access-key: ${AWS_ACCESS_KEY}
      region:
        static: ${AWS_REGION:ap-south-1}
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 8ef771af33ae62
    password: ${MAILTRAP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/bookshop_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ahnis123
    driver-class-name: com.mysql.cj.jdbc.Driver
  threads:
    virtual:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
logging:
  level:
    org.springframework.security: TRACE
    org.hibernate.SQL: DEBUG


cors:
  allowed-origins:
    - "http://localhost:5173"
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed-headers:
    - "*"
app:
  email:
    provider: "sendgrid"
  aws:
    s3:
      bucket-name: "bookstacks-images"
    sqs:
      notification-queue-url: ${SQS_NOTIFICATION_QUEUE_URL}
    ses:
      from-email: "noreply@bookstacks.store"
  frontend:
    url: http://localhost:5173
  cookie:
    secure: false
    domain: "localhost"
    same-site: "Lax"
    path: "/"
jwt:
  secret: ${JWT_SECRET_KEY}
  access-expiration: 900000 # 15 minutes in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds
