name: Frontend Deployment

on:
  push:
    branches: [ "master" ]
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build React App
        working-directory: ./frontend
        env:
          # Using your existing secret and dropping the 8080 port for the proxy!
          VITE_API_BASE_URL: http://${{ secrets.EC2_HOST }}/api/v1
        run: |
          npm install
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to S3
        working-directory: ./frontend
        run: aws s3 sync dist/ s3://bookstacks-frontend-prod --delete